Part 3
d90375/reactjs-films-homework pull request #4
Opened 2020-09-23 10:23 UTC by d90375

part-3

2020-10-02 15:45 UTC, RomanRudski requested changes

2020-10-02 15:45 UTC, RamanRudski commented on src/components/Header/Description/Rating/Rating.jsx
> +      {[...Array(roundedAverage)].map((item, index) => (
здесь не нужна spread операция, удали ее. Array() и так возвращает массив.

2020-10-02 15:45 UTC, RamanRudski commented on src/components/Header/Description/Rating/Rating.jsx
> +        <div key={`${item}${index}`} className="star">
для key возьми посто индекс. В данном случае `item === undefined`

2020-10-02 15:45 UTC, RamanRudski commented on src/components/Header/Description/Rating/Rating.jsx
>            <svg xmlns="http://www.w3.org/2000/svg" width="1rem" height="1rem" viewBox="0 0 36 36">
svg иконки должны храниться в отдельном файле. 
В данном случае лучше использовать иконочный шрифт  `&#9733;`

2020-10-02 15:45 UTC, RamanRudski commented on src/components/Header/Description/Rating/__tests__/__snapshots__/Rating.spec.js.snap
> +    key="undefined0"
в снэпшотах не должно быть `undefined`;

2020-10-02 15:45 UTC, RamanRudski commented on src/components/Header/Description/Rating/__tests__/Rating.spec.js
>      component = setUp();
тебе не нужен beforeEach, удали во всех местах

2020-10-02 15:45 UTC, RamanRudski commented on src/components/Header/Description/Rating/__tests__/Rating.spec.js
>  describe("Rating component", () => {
Давай будем писать в describe название компонента вот так `<Rating />`

2020-10-02 15:45 UTC, RamanRudski commented on src/components/Header/Header.jsx
> +  const voteAverage = headData.vote_average;
`voteAverage ` можно получить с помощью деструкторизации выше

2020-10-02 15:45 UTC, RamanRudski commented on src/components/Header/Header.jsx
> +  let poster = "";
нет смысла присваивать пустую строку

2020-10-02 15:45 UTC, RamanRudski commented on src/components/Header/Notation/Notation.container.jsx
> +  const handleHideView = () => {
 лучше назвать `handleToggleView`

2020-10-02 15:45 UTC, RamanRudski commented on src/components/Header/Search/Search.container.jsx
> +  const [queryText, setQueryText] = useState("");
это скорее `value` к `query` не имеет отношения.

2020-10-02 15:45 UTC, RamanRudski commented on src/components/Header/Search/Search.container.jsx
> +        onSubmit={onSubmit}
`onSubmit = { handleSubmit }` все что ты прокидываешь в пропсы это `handle`

2020-10-02 15:45 UTC, RamanRudski commented on src/components/Header/Search/Search.jsx
> +        <svg
`svg` выносяться в отдельный файл

2020-10-02 15:45 UTC, RamanRudski commented on src/components/Header/Search/Search.container.jsx
> +    if (event.key === "Enter") {
это не нужно, форма по дефолту работает на `Enter`. Перенеси диспатч в `onSubmit`

2020-10-02 15:45 UTC, RamanRudski commented on src/components/Header/Search/Search.jsx
> +  onSubmit: () => {}
вместо `defaultProps` для этих хэндлеров поставь в `propTypes` `onQueryChanged: PropTypes.func.isRequired`

2020-10-02 15:45 UTC, RamanRudski commented on src/components/MovieList/Card/Card.container.jsx
> +
лучше сделать что-то вроде `handleToggleWindow = () => { setIsHiddenWindow( ! isHiddenWindow) } `

2020-10-02 15:45 UTC, RamanRudski commented on src/components/MovieList/Card/Card.container.jsx
> +
тоже самое что и выше

2020-10-02 15:45 UTC, RamanRudski commented on src/components/MovieList/Card/Card.container.jsx
> +        id={cardItem?.id}
просто перейдай `cardItem` через пропс и уже вв дочернем компоненте, делай все что нужно

2020-10-02 15:45 UTC, RamanRudski commented on src/components/MovieList/Card/Card.scss
> +  &:nth-child(n+14) {
`:last-child`

2020-10-02 15:45 UTC, RamanRudski commented on src/components/MovieList/Card/HiddenWindow/__tests__/HiddenWindow.spec.js
> +      const result = HiddenWindow.defaultProps.onShowInfo();
в случаях когда тебе нужно протестить хэндлеры,  мокаешь хэндлер и пробрасываешь ,делаешь `shallow`, находишь нужную кнопку, симулируешь клик, и смотришь чтобы хэндлер вызвался.
Переделай во всех местах

2020-10-02 15:45 UTC, RomanRudski commented on src/components/MovieList/TopSort/TopSort.jsx
> +
сделай ОДИН экшн. что-то вроде  getListBy()и передавай туда како-то флаг (trending, rared, coming)

2020-10-02 15:45 UTC, RomanRudski commented on src/components/MovieList/TopSort/__tests__/TopSort.spec.js
> +      <Provider store={store}>
тебе сдесь не нужен стор, просто тести обычный компонент

2020-10-02 15:45 UTC, RomanRudski commented on src/components/VideoFrame/ButtonWatchNow/ButtonWatchNow.jsx
> +  const { handleShowTrailer } = useTrailerActions(movieId);
кнопку нельзя переюзать, ты ее сделал умной и она теперь специфичная

2020-10-02 15:45 UTC, RomanRudski commented on src/modules/headerData/headerSelectors.js
> +export const useCurrentMovieData = () => useSelector(getDataByIdSelector);
`useCurrentMovieData` это не хук, не нужно так делать. Используй реселект для создания селекторов. 
А потом в нужном компоненте ипользуй `useSelector`.

2020-10-02 15:45 UTC, RomanRudski commented on src/modules/headerData/headerSelectors.js
> +export const useCurrentMovie = () => useSelector((state) => state.header);
тоже самое

2020-10-02 17:08 UTC, RomanRudski requested changes

2020-10-02 17:08 UTC, RamanRudski commented on src/components/Header/Header.container.jsx
> +      .reduce((acc, genre) => {
`let finalGenres`

2020-10-04 13:27 UTC, d90375 commented on src/components/Header/Description/Rating/Rating.jsx
> +      {[...Array(roundedAverage)].map((item, index) => (
c empty проход по массиву не работает, только создает его length
делаем spread на каждый элемент массива с вэлью undefind

2020-10-04 14:57 UTC, d90375 commented on src/components/Header/Description/Rating/Rating.jsx
> +        <div key={`${item}${index}`} className="star">
fixed

2020-10-04 14:57 UTC, d90375 commented on src/components/Header/Description/Rating/Rating.jsx
>            <svg xmlns="http://www.w3.org/2000/svg" width="1rem" height="1rem" viewBox="0 0 36 36">
fixed

2020-10-04 14:58 UTC, d90375 commented on src/components/Header/Description/Rating/__tests__/__snapshots__/Rating.spec.js.snap
> +    key="undefined0"
fixed

2020-10-04 15:06 UTC, d90375 commented on src/components/Header/Description/Rating/__tests__/Rating.spec.js
>      component = setUp();
fixed

2020-10-04 15:07 UTC, d90375 commented on src/components/Header/Description/Rating/__tests__/Rating.spec.js
>  describe("Rating component", () => {
fixed

2020-10-04 15:08 UTC, d90375 commented on src/components/Header/Header.jsx
> +  const voteAverage = headData.vote_average;
i added a rule to ESLINT, fixed

2020-10-04 16:11 UTC, d90375 commented on src/components/Header/Search/Search.container.jsx
> +  const [queryText, setQueryText] = useState("");
fixed

2020-10-04 16:11 UTC, d90375 commented on src/components/Header/Notation/Notation.container.jsx
> +  const handleHideView = () => {
fixed

2020-10-04 16:11 UTC, d90375 commented on src/components/Header/Search/Search.container.jsx
> +        onSubmit={onSubmit}
fixed

2020-10-04 16:12 UTC, d90375 commented on src/components/Header/Search/Search.jsx
> +        <svg
fixed

2020-10-04 16:26 UTC, d90375 commented on src/components/Header/Search/Search.container.jsx
> +    if (event.key === "Enter") {
fixed

2020-10-04 17:00 UTC, d90375 commented on src/components/Header/Search/Search.jsx
> +  onSubmit: () => {}
fixed

2020-10-06 05:25 UTC, d90375 commented on src/components/MovieList/TopSort/TopSort.jsx
> +
fixed

2020-10-16 06:50 UTC, RomanRudski approved these changes

2020-10-16 11:42 UTC, merged